# Generated by Django 5.2.4 on 2025-08-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Progress', 'in-progress'), ('Finished', 'finished')], max_length=50, null=True),
        ),
    ]
